[tool.poetry]
name = "accounting_app"
version = "0.1.0"
description = "Accounting backend usando Clean Architecture con FastAPI"
authors = ["Tu Nombre <tu.email@example.com>"]
readme = "README.md"
packages = [{ include = "application" }, { include = "domain" }, { include = "infrastructure" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
fastapi = "^0.110.0"
uvicorn = "^0.29.0"
sqlalchemy = {version = "^2.0.41", extras = ["asyncio"]}
aiosqlite = "^0.21.0"
databases = "^0.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
