# Este archivo contiene los valores por defecto para los comandos de SAM CLI

version = 0.1

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
region = "us-east-1"

[development.deploy.parameters]
stack_name = "accounting-app-development"
s3_bucket = "tu-bucket-de-despliegue-aqui" # ¡IMPORTANTE! Reemplaza esto
s3_prefix = "accounting-app-development"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true

[production.deploy.parameters]
stack_name = "accounting-app-production"
s3_bucket = "tu-bucket-de-despliegue-aqui" # ¡IMPORTANTE! Reemplaza esto
s3_prefix = "accounting-app-production"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true

# =============================================================================
# Global Build Configuration
# =============================================================================
[default.build.parameters]
cached = true
parallel = true 